require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/churches", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Church. As you add validations to Church, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Church.create! valid_attributes
      get churches_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      church = Church.create! valid_attributes
      get church_url(church)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_church_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      church = Church.create! valid_attributes
      get edit_church_url(church)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Church" do
        expect {
          post churches_url, params: { church: valid_attributes }
        }.to change(Church, :count).by(1)
      end

      it "redirects to the created church" do
        post churches_url, params: { church: valid_attributes }
        expect(response).to redirect_to(church_url(Church.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Church" do
        expect {
          post churches_url, params: { church: invalid_attributes }
        }.to change(Church, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post churches_url, params: { church: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested church" do
        church = Church.create! valid_attributes
        patch church_url(church), params: { church: new_attributes }
        church.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the church" do
        church = Church.create! valid_attributes
        patch church_url(church), params: { church: new_attributes }
        church.reload
        expect(response).to redirect_to(church_url(church))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        church = Church.create! valid_attributes
        patch church_url(church), params: { church: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested church" do
      church = Church.create! valid_attributes
      expect {
        delete church_url(church)
      }.to change(Church, :count).by(-1)
    end

    it "redirects to the churches list" do
      church = Church.create! valid_attributes
      delete church_url(church)
      expect(response).to redirect_to(churches_url)
    end
  end
end
